- name: email-profiteers
  title: "Email Profiteers"
  url: /pages/email-profiteers/
  description: "Regarding email marketing, this book will be the last one you'll have to read. Step by step, complete guide to grow your profits from your email sending."
  image: email-profiteers.jpg
  gumroad: https://gum.co/Wzexs
  price: "$17"
  retail: "$37"

- name: the-tweet-succes-guide
  title: "The Tweet Success Guide"
  url: /pages/the-tweet-succes-guide
  description: "Powerful words can change the world! Powerful tweets will bring you profits! Way easier than changing the world."
  image: the-tweet-succes-guide.jpg
  gumroad: https://gum.co/UIAdx
  price: "$7"
  retail: "$27"

- name: insider-guide-to-forex-trading
  title: "Insider's Guide To Forex Trading"
  url: /pages/insider-guide-to-forex-trading
  description: "In an emerging economy like the one we're living nowadays, profiting from it's growth gets easy like 1,2,3 by using forex. Get your slice of the money pie now!"
  image: insider-guide-to-forex-trading.jpg
  gumroad: https://gum.co/MDlYE
  price: "$19"
  retail: "$39"

- name: internet-marketing-from-a-to-z
  title: "Internet Marketing from A to Z"
  url: /pages/internet-marketing-from-a-to-z
  description: "The purpose of a business is to make money. The field of marketing is the most valuable tool in the process of obtaining success from your business"
  image: internet-marketing-from-a-to-z.jpg
  gumroad: https://gum.co/TzCV
  price: "$14"
  retail: "$34"

- name: viral-marketing-values
  title: "Viral Marketing Values"
  url: /pages/viral-marketing-values
  description: "Internet has become the most efficient promoting tool worldwide. Learn how to use it with this easy to use and comprehensive guide!"
  image: viral-marketing-values.jpg
  gumroad: https://gum.co/DBOtL
  price: "$14"
  retail: "$34"

- name: prosperity-pursuit
  title: "Prosperity Pursuit"
  url: /pages/prosperity-pursuit
  description: "Humankind has discovered that becoming prosperous and wealthy is not achievable by chance, it is a science. Start the learning process today!"
  image: prosperity-pursuit.jpg
  gumroad: https://gum.co/lcSxC
  price: "$17"
  retail: "$37"

- name: social-media-power
  title: "Social Media Power"
  url: /pages/social-media-power
  description: "The news travels the fastest through social media. Every word and every second counts when it comes to your business."
  image: social-media-power.jpg
  gumroad: https://gum.co/geUmT
  price: "$17"
  retail: "$37"

- name: vegetarian-food-and-cooking
  title: "Vegetarian Food and Cooking"
  url: /pages/vegetarian-food-and-cooking
  description: "Living healthy is an investment in your family and yourself. Start with your food and you'll see the improvement in days! Your energy levels will skyrocket!"
  image: vegetarian-food-and-cooking.jpg
  gumroad: https://gum.co/Whzi
  price: "$17"
  retail: "$37"

- name: website-ideas
  title: "Website Ideas"
  url: /pages/website-ideas
  description: "As any book is just pages put together and indexed, the Internet is just websites linked together by the search engines. Make sure yours is worthy of it! "  
  gumroad: https://gum.co/RZLN
  price: "$17"
  retail: "$37"
  image: website-ideas.jpg

- name: eliminate-stress
  title: "Eliminate Stress"
  url: /pages/eliminate-stress
  description: "Stress has a worse influence on your health than a lot of poisonous chemicals. Cleanse your body and mind of this poison and start living a better life!"  
  gumroad: https://gum.co/Xkebh
  price: "$17"
  retail: "$37"
  image: eliminate-stress.jpg

- name: dating-digest
  title: "Dating Digest"
  url: /pages/dating-digest
  description: "The mysteries of the human mind when dating has baffled even the smartest scientists for a long time. Here's the conclusion of their successful studies."  
  gumroad: https://gum.co/wfqK
  price: "$17"
  retail: "$37"
  image: dating-digest.png

- name: body-fat-inferno
  title: "Body Fat Inferno"
  url: "/pages/body-fat-inferno/"
  description: "Your self esteem and general health skyrockets when you take care of your body. Therefore, the quality of your life gets a well deserved boost."  
  gumroad: https://gum.co/XFCsW
  price: "$27"
  retail: "$47"
  image: "body-fat-inferno.png"

- name: entrepreneurs
  title: "Entrepreneurs"
  url: /pages/entrepreneurs
  description: "Taking charge of your life is a challenge, but the satisfaction is a million times better than any promotion from any job. Stop procrastinating and start today!"
  image: entrepreneurs.jpg
  gumroad: https://gum.co/Icqbi
  price: "$17"
  retail: "$37"

- name: internet-marketing
  title: "Internet Marketing"
  url: /pages/internet-marketing
  description: "Extremely profitable for the trained individual, internet marketing is a growing worldwide industry. Get going today towards financial freedom!"
  image: internet-marketing.jpg
  gumroad: https://gum.co/ywjU
  price: "$17"
  retail: "$37"

- name: online-poker
  title: "Online Poker"
  url: /pages/online-poker
  description: "Emerging from a simple card game to a worldwide phenomenon, poker has become a social glue and a money making method. Know your game!"
  image: online-poker.jpg
  gumroad: https://gum.co/YPsj
  price: "$17"
  retail: "$37"