- name: email-profiteers
  title: "Email Profiteers"
  url: /pages/email-profiteers/
  short_description: "1Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: email-profiteers.jpg
  gumroad: https://gum.co/Wzexs
  price: "$19.991"
  keywords: 

- name: Entrepreneurs
  title: "Entrepreneurs"
  url: /pages/Entrepreneurs
  short_description: "2Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: Entrepreneurs.jpg
  gumroad: https://gum.co/Icqbi
  price: "$19.992"

- name: ForexTrading
  title: "Forex Trading"
  url: /pages/ForexTrading
  short_description: "3Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: ForexTrading.jpg
  gumroad: https://gum.co/UXbO
  price: "$19.993"

- name: InternetMarketing
  title: "Internet Marketing"
  url: /pages/InternetMarketing
  short_description: "6Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: InternetMarketing.jpg
  gumroad: https://gum.co/ywjU
  price: "$19.996"

- name: OnlinePoker
  title: "Online Poker"
  url: /pages/OnlinePoker
  short_description: "7Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: OnlinePoker.jpg
  gumroad: https://gum.co/YPsj
  price: "$19.997"

- name: ProsperityPursuit
  title: "Prosperity Pursuit"
  url: /pages/ProsperityPursuit
  short_description: "8Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: ProsperityPursuit.jpg
  gumroad: https://gum.co/lcSxC
  price: "$19.998"

- name: SocialMediaPower
  title: "Social Media Power"
  url: /pages/SocialMediaPower
  short_description: "9Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: SocialMediaPower.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.999"

- name: VegetarianFoodandCooking
  title: "Vegetarian Food and Cooking"
  url: /pages/VegetarianFoodandCooking
  short_description: "10Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: VegetarianFoodandCooking.jpg
  gumroad: https://gum.co/Whzi
  price: "$19.999"

- name: WebsiteIdeas
  title: "Website Ideas"
  url: /pages/WebsiteIdeas
  short_description: "11Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"  
  gumroad: https://gum.co/RZLN
  price: "$19.9911"
  image: WebsiteIdeas.jpg

- name: EliminateStress
  title: "Eliminate Stress"
  url: /pages/EliminateStress
  short_description: "11Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"  
  gumroad: https://gum.co/Xkebh
  price: "$19.9911"
  image: EliminateStress.jpg

- name: DatingDigest
  title: "Dating Digest"
  url: /pages/DatingDigest
  short_description: "11Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"  
  gumroad: https://gum.co/wfqK
  price: "$19.9911"
  image: DatingDigest.png

- name: "body-fat-inferno"
  title: "Body Fat Inferno"
  url: "/pages/body-fat-inferno/"
  short_description: "11Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"  
  gumroad: https://gum.co/XFCsW
  price: "$27"
  image: "body-fat-inferno.png"