- name: EmailProfiteers
  url: /pages/EmailProfiteers
  title: "Email Profiteers"
  short_description: "1Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: EmailProfiteers.jpg
  gumroad: https://gum.co/zvKqj
  price: "$19.991"

- name: Entrepreneurs
  url: /pages/Entrepreneurs
  title: "Entrepreneurs"
  short_description: "2Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: Entrepreneurs.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.992"

- name: ForexTrading
  url: /pages/ForexTrading
  title: "Forex Trading"
  short_description: "3Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: ForexTrading.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.993"

- name: ForexTrading1
  url: /pages/ForexTrading1
  title: "Forex Trading 1"
  short_description: "4Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: ForexTrading1.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.994"

- name: ForexTradingRevolution
  url: /pages/ForexTradingRevolution
  title: "Forex Trading Revolution"
  short_description: "5Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: ForexTradingRevolution.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.995"

- name: InternetMarketing
  url: /pages/InternetMarketing
  title: "Internet Marketing"
  short_description: "6Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: InternetMarketing.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.996"

- name: OnlinePoker
  url: /pages/OnlinePoker
  title: "Online Poker"
  short_description: "7Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: OnlinePoker.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.997"

- name: ProsperityPursuit
  url: /pages/ProsperityPursuit
  title: "Prosperity Pursuit"
  short_description: "8Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: ProsperityPursuit.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.998"

- name: SocialMediaPower
  url: /pages/SocialMediaPower
  title: "Social Media Power"
  short_description: "9Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"
  image: SocialMediaPower.jpg
  gumroad: https://gum.co/XXXX
  price: "$19.999"

- name: TrademarkingCover
  url: /pages/TrademarkingCover
  title: "Trademarking Cover"
  short_description: "10Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"  
  gumroad: https://gum.co/XXXX
  price: "$19.9910"
  image: TrademarkingCover.jpg

- name: DatingDigest
  url: /pages/DatingDigest
  title: "Dating Digest"
  short_description: "11Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"  
  gumroad: https://gum.co/XXXX
  price: "$19.9911"
  image: DatingDigest.png

- name: BodyFatInferno
  url: /pages/BodyFatInferno
  title: "Body Fat Inferno"
  short_description: "11Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis, voluptatum?"  
  gumroad: https://gum.co/XXXX
  price: "$19.9911"
  image: BodyFatInferno.png